apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-postgres
spec:
  replica: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: db-postgresql
        image: postgresql:16.4-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
