apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: db-postgresql
        image: postgres:16.4-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: pg-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: common-secret
              key: pg-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: common-secret
              key: pg-password

---
apiVersion: v1
kind: Service
metadata:
  name: service-postgres
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
