apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-webApp
spec:
  replica: 2
  selector:
    matchLabels:
      app: webApp
  template:
    metadata:
      labels:
        app: webApp
    spec:
      containers:
      - name: webApp101
        image: gateway-scheduler/v2
        resources:
          limits:
            memory: "400Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: service-webApp
spec:
  selector:
    app: webApp
  ports:
  - protocol: TCP
    port: 7777
    targetPort: 8080
