apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp101
        image: gateway-scheduler:v2
        resources:
          limits:
            memory: "400Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        

        env:
          - name: APP_SERVICE_NAME
            valueFrom:
              configMapKeyRef:
                name: common-config
                key: app-name
          - name: APP_SERVER_MODE
            valueFrom:
              configMapKeyRef:
                name: common-config
                key: app-mode
          - name: APP_SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: common-config
                key: app-port
          - name: APP_SERVER_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: common-config
                key: app-timeout
          - name: APP_LOGGER_LOG_FILE_PATH
            valueFrom:
              configMapKeyRef:
                name: common-config
                key: app-log-path
          - name: APP_APP_VALIDATE_X_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: common-secret
                key: app-secret
          - name: APP_DATABASE_POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: common-config
                key: pg-url
          - name: APP_DATABASE_POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                name: common-config
                key: pg-port
          - name: APP_DATABASE_POSTGRES_DBNAME
            valueFrom:
              configMapKeyRef:
                name: common-config
                key: pg-db
          - name: APP_DATABASE_POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: common-secret
                key: pg-user
          - name: APP_DATABASE_POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: common-secret
                key: pg-password
          - name: APP_CLIENTS_GATEWAY_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: common-config
                key: app-client-url
          - name: APP_CLIENTS_GATEWAY_X_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: common-secret
                key: app-client-secret

---
apiVersion: v1
kind: Service
metadata:
  name: service-webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8080
    nodePort: 30001
