apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ing-mongo-express
spec:
  tls:
  - hosts:
    - localhost
    secretName: sec-tls
  rules:
  - host: localhost
    http:
      paths:
      - path: /api
        backend:
          serviceName: svc-mongo-express
          servicePort: 80