apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  labels:
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
        component: backend
    spec:
      containers:
      - name: spring-boot-container
        image: your-docker-image:latest # Replace with your image
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
