apiVersion: v1
kind: Service
metadata:
  name: spring-boot-backend-service
  labels:
    component: backend
spec:
  selector:
    app: spring-boot-app # Matches the app label in the Deployment
  ports:
    - protocol: TCP
      port: 80           # Service's port (other backend services use this)
      targetPort: 8080   # Pod's port
  type: ClusterIP        # Makes the service internal to the cluster
